### ISSUE TITLE
Submit conda-forge recipe

### ISSUE THREAD

**Issue by ericdill** [maxpoint/kernda#5]
@parente I wanted to use this today but there's no conda package yet :crying_cat_face: 

We probably need another tag for this.  Would you suggest 0.0.4 or 0.1.0?

**Comment by parente** [comment]
Current master is CLI incompatible with 0.0.4 (removed redundant yes flag IIRC) so 0.1.0.

**Comment by parente** [comment]
https://github.com/conda-forge/staged-recipes/pull/2449
